### ISSUE TITLE
Request extention link should not be added on the enrol page

### ISSUE THREAD

**Issue by brendanheywood** [central-queensland-uni/moodle-local_extension#17]
ie if I go to a course I am not enrolled in:

![image](https://cloud.githubusercontent.com/assets/187449/18674519/d5da0f32-7f92-11e6-8a85-bc8256428882.png)

**Comment by nhoobin** [comment]
The navigation item should only be displayed if a user is already enrolled in the course.

https://github.com/central-queensland-uni/moodle-local_extension/blob/cdaefe50de570ed0c0fd918266589b78668a5acb/lib.php#L61
https://github.com/central-queensland-uni/moodle-local_extension/blob/cdaefe50de570ed0c0fd918266589b78668a5acb/lib.php#L99

I can't see that error with the latest version, so I will close this and we can reopen it if is necessary.
