### ISSUE TITLE
Add admin configuration item for the extension policy.

### ISSUE THREAD

**Issue by nhoobin** [central-queensland-uni/moodle-local_extension#2]
- [x] Add the two configuration items
- [x] Implement the content on the request page
- [x] Implement the content on the status page

**Comment by brendanheywood** [comment]
Make this two html wysiwyg areas, one for the status html page header, and one for the request page header

**Comment by nhoobin** [comment]
@brendanheywood Does this mean the admin config page will be an external admin page as a form, to provide the editor wysiwyg?

**Comment by brendanheywood** [comment]
look at admin_setting_confightmleditor, you don't need a new settings page
