### ISSUE TITLE
Modification of extension length comment only shows the largest unit.

### ISSUE THREAD

**Issue by nhoobin** [central-queensland-uni/moodle-local_extension#39]
The comment that is recorded truncates the length to the largest unit.

An update of 1 day 1 hour will display the length is 1 day.

**Comment by brendanheywood** [comment]
This is all redundant, just call format_time() and it does this already. get_extension_length() went to lengths to remove the second time component! :)

**Comment by nhoobin** [comment]
Moodle's format_time() function will truncate the output to the largest two units of time. If we set the extension length to 2d 2h 30m it will only print 2d 2h. The date selector that we are using allows minutes to be selected. 

I think we should be printing the full resolution of time for the request. Users should know if they still have +x minutes left on the clock, or if it was due on the half hour.
